import React, { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom';
//imported for creating toast pop-up
import M from 'materialize-css';

export const Createpost = () => {
    const history=useNavigate();
    const [title,settitle]=useState("");
    const [body,setbody]=useState("");   
    const [image,setimage]=useState(""); //image also a type of string because, we get path when we use file upload at files[0] postion
    //here we use image state to generate url using cloudinary and url which is generated by it is saved inside url state, ,and this url is passed to mongoDB
    const [url, seturl]=useState("");

    // useEffect with url as dependency, this way when url is fetched than only
    // posting to DB starts, if we dont use this useEffect both processes become concurrent and can
    // cause problem
    useEffect(() => {
      if(url){
        //posting data to /createpost
        fetch("/createpost",{
          method:"post",
          headers:{
            "Content-Type":"application/json",
            "Authorization":"Bearer "+localStorage.getItem("jwt")
          },
          body:JSON.stringify(
            {
              title:title,
              body:body,
              url:url
            }
          )  
          }).then(res=>res.json()).then(data=>{
            if(data.error){
              M.toast({html:data.error,classes:"#c62828 red darken-3"})
            }
            else{
              M.toast({html:"Post Created Successfully",classes:"#ce93d8 purple lighten-3"})
              //redirecting to home page after we successfully sign up 
              history('/home')
            }
          }).catch(err=>{
            console.log(err)
          })
      }
    }, [url])
    

    //we are uploading our image to cloudinary cloud and the url which is provided by cloudinary we save
    //it to our mongoDB
    const postDetails=()=>{
        if(image==""||title==""||body==""){
          return M.toast({html:"Please Fill All Fields",classes:"#c62828 red darken-3"})
        }

        //this section is used for uploading the photo to cloudinary and generating url
        const data=new FormData();
        data.append("file",image);
        data.append("upload_preset","socialnetworking");
        data.append("cloud_name","lokindercloud")
        fetch('https://api.cloudinary.com/<YOUR CLOUDINARY API>',{
            method:"post",
            body:data
        }).then(res=>res.json())
        .then(data=>{
            seturl(data.url);
        }).catch(err=>{
            console.log(err)
        })
    }

  return (
    <div className='card input-filed' style={{
        margin:"90px auto",
        maxWidth:"500px",
        padding:"20px",
        borderRadius:"20px",
        textAlign:"center",
        backgroundColor:"#FAF9F6"
    }}>
        <h3>New Post</h3>
        <input 
            type="text"
            placeholder="Title"
            value={title}
            onChange={(e)=>{
                settitle(e.target.value);
            }}
        />
        <input 
            type="text"
            placeholder="Description"
            value={body}
            onChange={(e)=>{
                setbody(e.target.value);
            }}
        />
        <div className='file-field input-field'>
            <div className="btn #0d47a1 blue darken-3" style={{
              borderRadius:"10px"
            }}>
            <span >Upload Photo</span>
                <input type="file"
                onChange={(e)=>{
                    setimage(e.target.files[0]);
                }}
                />
            </div>
            <div className="file-path-wrapper" >
                <input className="file-path validate" type="text"/>
            </div>
        </div>
        <button style={{
              borderRadius:"10px"
            }} className="btn waves-effect waves-light #0d47a1 blue darken-3" type="submit" name="action"
        onClick={()=>{
            postDetails();
        }}>Upload Post
          <i className="material-icons right">send</i>
        </button>
    </div>
  )
}
